name: Tool for Comma10k

# Trigger the workflow on push or pull request
on:
  push:
    branches:
      - '*'
    tags:
      - 'v*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: git fetch origin +refs/tags/*:refs/tags/*
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        name: Install OxiPNG
        with:
          command: install
          args: --root cargo_root -- oxipng
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - run: pip install -r requirements.txt
      - run: pip install pyinstaller
      - run: pyinstaller -y server.spec
      - name: Archive Dist
        run: 7z a -mx9 dist.zip .\dist\Tool4Comma10k\*
      - name: Archive Server Dist
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: dist.zip
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        if: startsWith(github.ref, 'refs/tags/')
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./dist.zip
          asset_name: tool4comma10k.zip
          asset_content_type: application/zip